// Lesson Notebook Types
export interface VocabularyEntry {
  term: string;
  definition: string;
  pronunciation: string;
  exampleSentence?: string;
}

export interface Correction {
  original: string;
  corrected: string;
  explanation: string;
  rule: string;
}

export interface LessonNotebook {
  lessonId: string;
  date: string;
  lessonTitle: string;
  autoGeneratedNotes: string;
  personalNotes: string;
  vocabularyLearned: VocabularyEntry[];
  corrections: Correction[];
  achievements: string[];
  culturalMoments: string[];
  practiceGuidance: string;
}

// Database response interface (matches Supabase schema)
export interface LessonNotebookDBResponse {
  id: string;
  lesson_id: string;
  lesson_title: string;
  user_id: string;
  auto_notes: string | null;
  personal_notes: string | null;
  vocabulary_json: VocabularyEntry[] | null;
  corrections_json: Correction[] | null;
  achievements_json: string[] | null;
  cultural_moments_json: string[] | null;
  practice_guidance: string | null;
  created_at: string;
  updated_at: string;
}