// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnamcueqybonhtxzyvts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuYW1jdWVxeWJvbmh0eHp5dnRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjgwNzIsImV4cCI6MjA3MTIwNDA3Mn0.bMlF6LUPdlD_gZZjkHhgK63Ge4tKEI59fneERQJBakk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});